### ISSUE TITLE
after run cjmx EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by korimo** [cjmx/cjmx#19]
A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000061fdcab8, pid=12708, tid=2524

 JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 V  [jvm.dll+0x11cab8]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

---------------  T H R E A D  ---------------

Current thread (0x000000000289e000):  JavaThread "main" [_thread_in_vm, id=2524, stack(0x00000000028a0000,0x00000000029a0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000000289e000, RCX=0x000000000289e000, RDX=0x00000007d6204350
RSP=0x000000000299cfe0, RBP=0x0000000000000100, RSI=0x0000000000000100, RDI=0x0000000000000000
R8 =0x0000000000000000, R9 =0x0000000000000100, R10=0x0000000000000000, R11=0x000000000299d020
R12=0x0000000000000000, R13=0x000000077cfa1298, R14=0x000000000299d100, R15=0x000000000289e000
RIP=0x0000000061fdcab8, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000000299cfe0)
0x000000000299cfe0:   0000000000000053 0000000800000009
0x000000000299cff0:   000000000cc4e328 000000000289e000
0x000000000299d000:   0000000000000000 00000000ef8b631a
0x000000000299d010:   000000000289d860 0000000061f5fce8
0x000000000299d020:   000000000289e000 000000000cc4e308
0x000000000299d030:   0000000000000b9d 00000000624470c0
0x000000000299d040:   000000000299d0f8 00007ffd36bc1ba7
0x000000000299d050:   00000000a2e2e77c 00000000625b7f80
0x000000000299d060:   000000000289e1e8 0000000000000000
0x000000000299d070:   0000000000000000 0000000002ab3150
0x000000000299d080:   000000077cfa1298 000000000299d0e8
0x000000000299d090:   00000000ef8b631a 0000000002aa60f8
0x000000000299d0a0:   000000000289e000 000000000299d0a8
0x000000000299d0b0:   000000077cfa1298 000000000299d100
0x000000000299d0c0:   000000077cfa22c0 0000000000000000
0x000000000299d0d0:   000000077cfa1298 0000000000000000 

Instructions: (pc=0x0000000061fdcab8)
0x0000000061fdca98:   24 38 c6 44 24 30 53 33 d2 48 8b cb c6 44 24 28
0x0000000061fdcaa8:   01 66 89 74 24 70 48 89 7c 24 20 e8 48 e0 06 00
0x0000000061fdcab8:   48 8b 07 48 63 57 10 48 8b 48 78 66 89 34 0a 48
0x0000000061fdcac8:   83 7c 24 48 00 74 0a 48 8d 4c 24 40 e8 67 34 11 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000000289e000 is a thread
RCX=0x000000000289e000 is a thread
RDX=0x00000007d6204350 is an oop
java.lang.NoSuchFieldError 
- klass: 'java/lang/NoSuchFieldError'
  RSP=0x000000000299cfe0 is pointing into the stack for thread: 0x000000000289e000
  RBP=0x0000000000000100 is an unknown value
  RSI=0x0000000000000100 is an unknown value
  RDI=0x0000000000000000 is an unknown value
  R8 =0x0000000000000000 is an unknown value
  R9 =0x0000000000000100 is an unknown value
  R10=0x0000000000000000 is an unknown value
  R11=0x000000000299d020 is pointing into the stack for thread: 0x000000000289e000
  R12=0x0000000000000000 is an unknown value
  R13=0x000000077cfa1298 is an oop
  {method} 
- klass: {other class}
  R14=0x000000000299d100 is pointing into the stack for thread: 0x000000000289e000
  R15=0x000000000289e000 is a thread

Stack: [0x00000000028a0000,0x00000000029a0000],  sp=0x000000000299cfe0,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x11cab8]

[error occurred during error reporting (printing native stack), id 0xc0000005]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.fusesource.jansi.internal.Kernel32.init()V+0
j  org.fusesource.jansi.internal.Kernel32.<clinit>()V+20
v  ~StubRoutines::call_stub
j  org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>()V+0
v  ~StubRoutines::call_stub
j  org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;+42
j  org.fusesource.jansi.AnsiConsole.<clinit>()V+13
v  ~StubRoutines::call_stub
j  jline.AnsiWindowsTerminal.detectAnsiSupport()Z+7
j  jline.AnsiWindowsTerminal.<init>()V+5
v  ~StubRoutines::call_stub
j  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Ljava/lang/reflect/Constructor;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeConstructorAccessorImpl.newInstance([Ljava/lang/Object;)Ljava/lang/Object;+72
j  sun.reflect.DelegatingConstructorAccessorImpl.newInstance([Ljava/lang/Object;)Ljava/lang/Object;+5
j  java.lang.reflect.Constructor.newInstance([Ljava/lang/Object;)Ljava/lang/Object;+79
j  java.lang.Class.newInstance()Ljava/lang/Object;+132
j  jline.TerminalFactory.getFlavor(Ljline/TerminalFactory$Flavor;)Ljline/Terminal;+18
j  jline.TerminalFactory.create()Ljline/Terminal;+203
j  jline.TerminalFactory.get()Ljline/Terminal;+14
j  sbt.JLine$.sbt$JLine$$terminal()Ljline/Terminal;+0
j  sbt.JLine$.withTerminal(Lscala/Function1;)Ljava/lang/Object;+1
j  sbt.JLine$.usingTerminal(Lscala/Function1;)Ljava/lang/Object;+9
j  sbt.JLine$.createReader(Lscala/Option;)Ljline/console/ConsoleReader;+9
j  sbt.FullReader.<init>(Lscala/Option;Lsbt/complete/Parser;Z)V+14
j  cjmx.App$$anonfun$1.apply(Lsbt/complete/Parser;)Lsbt/FullReader;+19
j  cjmx.App$$anonfun$1.apply(Ljava/lang/Object;)Ljava/lang/Object;+5
j  cjmx.App$$anonfun$cjmx$App$$prefixedReader$1$$anon$2$$anonfun$readLine$1.apply()Lscala/Option;+17
j  cjmx.App$$anonfun$cjmx$App$$prefixedReader$1$$anon$2$$anonfun$readLine$1.apply()Ljava/lang/Object;+1
j  scala.Option.orElse(Lscala/Function0;)Lscala/Option;+8
j  cjmx.App$$anonfun$cjmx$App$$prefixedReader$1$$anon$2.readLine(Ljava/lang/String;Lscala/Option;)Lscala/Option;+24
j  cjmx.cli.REPL$.readLine$1(Lscala/Function1;Lsbt/complete/Parser;)Lscala/Option;+31
j  cjmx.cli.REPL$.runR$1(Lcjmx/cli/ActionContext;Lscala/Function1;Ljava/io/PrintStream;Lscalaz/stream/Process;)I+104
j  cjmx.cli.REPL$.run(Lscala/Function1;Ljava/io/PrintStream;)I+82
j  cjmx.App$.run([Ljava/lang/String;)I+105
j  cjmx.Main$.main([Ljava/lang/String;)V+4
j  cjmx.Main.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x000000000c9a7800 JavaThread "JMX client heartbeat 2" daemon [_thread_blocked, id=11652, stack(0x000000000d970000,0x000000000da70000)]
  0x000000000ca96800 JavaThread "RMI Scheduler(0)" daemon [_thread_blocked, id=12416, stack(0x000000000d870000,0x000000000d970000)]
  0x000000000ccf5000 JavaThread "GC Daemon" daemon [_thread_blocked, id=11588, stack(0x000000000d770000,0x000000000d870000)]
  0x000000000ccf4800 JavaThread "RMI RenewClean-[192.168.9.71:61945]" daemon [_thread_blocked, id=9884, stack(0x000000000d670000,0x000000000d770000)]
  0x000000000adc6800 JavaThread "Service Thread" daemon [_thread_blocked, id=12464, stack(0x000000000c530000,0x000000000c630000)]
  0x000000000adbf800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=12736, stack(0x000000000c430000,0x000000000c530000)]
  0x000000000adbd800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=12092, stack(0x000000000c330000,0x000000000c430000)]
  0x000000000adbc800 JavaThread "Attach Listener" daemon [_thread_blocked, id=11192, stack(0x000000000c230000,0x000000000c330000)]
  0x000000000adb9800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=5588, stack(0x000000000c130000,0x000000000c230000)]
  0x000000000ad7f800 JavaThread "Finalizer" daemon [_thread_blocked, id=11288, stack(0x000000000c030000,0x000000000c130000)]
  0x000000000ad76800 JavaThread "Reference Handler" daemon [_thread_blocked, id=4992, stack(0x000000000bf30000,0x000000000c030000)]
=>0x000000000289e000 JavaThread "main" [_thread_in_vm, id=2524, stack(0x00000000028a0000,0x00000000029a0000)]

Other Threads:
  0x000000000ad72800 VMThread [stack: 0x000000000be30000,0x000000000bf30000] [id=5504]
  0x000000000addc000 WatcherThread [stack: 0x000000000c630000,0x000000000c730000] [id=12028]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap
 PSYoungGen      total 38400K, used 5948K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 17% used [0x00000007d5c80000,0x00000007d624f000,0x00000007d7d00000)
  from space 5120K, 0% used [0x00000007d8200000,0x00000007d8200000,0x00000007d8700000)
  to   space 5120K, 0% used [0x00000007d7d00000,0x00000007d7d00000,0x00000007d8200000)
 ParOldGen       total 86016K, used 1189K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 1% used [0x0000000781600000,0x0000000781729528,0x0000000786a00000)
 PSPermGen       total 21504K, used 11936K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 55% used [0x000000077c400000,0x000000077cfa82f8,0x000000077d900000)

Card table byte_map: [0x0000000005b60000,0x0000000005f80000] byte_map_base: 0x0000000001f7e000

Polling page: 0x0000000000f20000

Code Cache  [0x0000000002aa0000, 0x0000000002d10000, 0x0000000005aa0000)
 total_blobs=357 nmethods=95 adapters=215 free_code_cache=48507Kb largest_free_block=49640128

Compilation events (10 events):
Event: 4.128 Thread 0x000000000adbd800   91             java.lang.String::substring (79 bytes)
Event: 4.141 Thread 0x000000000adbd800 nmethod 91 0x0000000002b364d0 code [0x0000000002b36620, 0x0000000002b36978]
Event: 4.218 Thread 0x000000000adbd800   92             sun.misc.URLClassPath::getResource (74 bytes)
Event: 4.257 Thread 0x000000000adbf800 nmethod 90 0x0000000002b3cad0 code [0x0000000002b3cd80, 0x0000000002b3e598]
Event: 4.310 Thread 0x000000000adbf800   94   !         sun.misc.URLClassPath$JarLoader::getResource (91 bytes)
Event: 4.352 Thread 0x000000000adbf800 nmethod 94 0x0000000002b38790 code [0x0000000002b38980, 0x0000000002b39060]
Event: 4.403 Thread 0x000000000adbd800 nmethod 92 0x0000000002b43e50 code [0x0000000002b441c0, 0x0000000002b46a70]
Event: 4.430 Thread 0x000000000adbf800   95             java.util.HashMap::transfer (115 bytes)
Event: 4.444 Thread 0x000000000adbf800 nmethod 95 0x0000000002b36c10 code [0x0000000002b36d60, 0x0000000002b37048]
Event: 4.459 Thread 0x000000000adbd800   96 %           sun.misc.URLClassPath::getResource @ 39 (74 bytes)

GC Heap History (6 events):
Event: 2.785 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 38400K, used 33280K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 100% used [0x00000007d5c80000,0x00000007d7d00000,0x00000007d7d00000)
  from space 5120K, 0% used [0x00000007d8200000,0x00000007d8200000,0x00000007d8700000)
  to   space 5120K, 0% used [0x00000007d7d00000,0x00000007d7d00000,0x00000007d8200000)
 ParOldGen       total 86016K, used 0K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 0% used [0x0000000781600000,0x0000000781600000,0x0000000786a00000)
 PSPermGen       total 21504K, used 8362K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 38% used [0x000000077c400000,0x000000077cc2aaa0,0x000000077d900000)
Event: 2.808 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 38400K, used 4947K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 0% used [0x00000007d5c80000,0x00000007d5c80000,0x00000007d7d00000)
  from space 5120K, 96% used [0x00000007d7d00000,0x00000007d81d4d58,0x00000007d8200000)
  to   space 5120K, 0% used [0x00000007d8200000,0x00000007d8200000,0x00000007d8700000)
 ParOldGen       total 86016K, used 8K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 0% used [0x0000000781600000,0x0000000781602000,0x0000000786a00000)
 PSPermGen       total 21504K, used 8362K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 38% used [0x000000077c400000,0x000000077cc2aaa0,0x000000077d900000)
}
Event: 3.565 GC heap before
{Heap before GC invocations=2 (full 0):
 PSYoungGen      total 38400K, used 11218K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 18% used [0x00000007d5c80000,0x00000007d629fc08,0x00000007d7d00000)
  from space 5120K, 96% used [0x00000007d7d00000,0x00000007d81d4d58,0x00000007d8200000)
  to   space 5120K, 0% used [0x00000007d8200000,0x00000007d8200000,0x00000007d8700000)
 ParOldGen       total 86016K, used 8K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 0% used [0x0000000781600000,0x0000000781602000,0x0000000786a00000)
 PSPermGen       total 21504K, used 10355K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 48% used [0x000000077c400000,0x000000077ce1cc90,0x000000077d900000)
Event: 3.576 GC heap after
Heap after GC invocations=2 (full 0):
 PSYoungGen      total 38400K, used 1296K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 0% used [0x00000007d5c80000,0x00000007d5c80000,0x00000007d7d00000)
  from space 5120K, 25% used [0x00000007d8200000,0x00000007d8344010,0x00000007d8700000)
  to   space 5120K, 0% used [0x00000007d7d00000,0x00000007d7d00000,0x00000007d8200000)
 ParOldGen       total 86016K, used 16K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 0% used [0x0000000781600000,0x0000000781604000,0x0000000786a00000)
 PSPermGen       total 21504K, used 10355K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 48% used [0x000000077c400000,0x000000077ce1cc90,0x000000077d900000)
}
Event: 3.576 GC heap before
{Heap before GC invocations=3 (full 1):
 PSYoungGen      total 38400K, used 1296K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 0% used [0x00000007d5c80000,0x00000007d5c80000,0x00000007d7d00000)
  from space 5120K, 25% used [0x00000007d8200000,0x00000007d8344010,0x00000007d8700000)
  to   space 5120K, 0% used [0x00000007d7d00000,0x00000007d7d00000,0x00000007d8200000)
 ParOldGen       total 86016K, used 16K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 0% used [0x0000000781600000,0x0000000781604000,0x0000000786a00000)
 PSPermGen       total 21504K, used 10355K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 48% used [0x000000077c400000,0x000000077ce1cc90,0x000000077d900000)
Event: 3.693 GC heap after
Heap after GC invocations=3 (full 1):
 PSYoungGen      total 38400K, used 0K [0x00000007d5c80000, 0x00000007d8700000, 0x0000000800000000)
  eden space 33280K, 0% used [0x00000007d5c80000,0x00000007d5c80000,0x00000007d7d00000)
  from space 5120K, 0% used [0x00000007d8200000,0x00000007d8200000,0x00000007d8700000)
  to   space 5120K, 0% used [0x00000007d7d00000,0x00000007d7d00000,0x00000007d8200000)
 ParOldGen       total 86016K, used 1189K [0x0000000781600000, 0x0000000786a00000, 0x00000007d5c80000)
  object space 86016K, 1% used [0x0000000781600000,0x0000000781729528,0x0000000786a00000)
 PSPermGen       total 21504K, used 10339K [0x000000077c400000, 0x000000077d900000, 0x0000000781600000)
  object space 21504K, 48% used [0x000000077c400000,0x000000077ce18f58,0x000000077d900000)
}

Deoptimization events (9 events):
Event: 1.223 Thread 0x000000000289e000 Uncommon trap: reason=unloaded action=reinterpret pc=0x0000000002b09e48 method=sun.misc.URLClassPath.getLoader(I)Lsun/misc/URLClassPath$Loader; @ 113
Event: 1.388 Thread 0x000000000289e000 Uncommon trap: reason=null_check action=make_not_entrant pc=0x0000000002b13904 method=java.util.jar.JarFile.getJarEntry(Ljava/lang/String;)Ljava/util/jar/JarEntry; @ 5
Event: 1.549 Thread 0x000000000289e000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002b0b820 method=java.util.regex.Matcher.match(II)Z @ 86
Event: 1.549 Thread 0x000000000289e000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002b0b820 method=java.util.regex.Matcher.match(II)Z @ 86
Event: 1.549 Thread 0x000000000289e000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002b0b820 method=java.util.regex.Matcher.match(II)Z @ 86
Event: 1.549 Thread 0x000000000289e000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000002b0b820 method=java.util.regex.Matcher.match(II)Z @ 86
Event: 1.707 Thread 0x000000000289e000 Uncommon trap: reason=unreached action=reinterpret pc=0x0000000002b15a24 method=java.lang.AbstractStringBuilder.append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder; @ 1
Event: 4.414 Thread 0x000000000289e000 Uncommon trap: reason=null_check action=make_not_entrant pc=0x0000000002b08648 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8
Event: 4.443 Thread 0x000000000289e000 Uncommon trap: reason=unreached action=reinterpret pc=0x0000000002b23100 method=java.util.TreeMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @ 55

Internal exceptions (10 events):
Event: 4.448 Thread 0x000000000289e000 Threw 0x00000007d61c5c98 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.450 Thread 0x000000000289e000 Threw 0x00000007d61cff60 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.451 Thread 0x000000000289e000 Threw 0x00000007d61d3a70 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.455 Thread 0x000000000289e000 Threw 0x00000007d61d6910 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.457 Thread 0x000000000289e000 Threw 0x00000007d61db748 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.458 Thread 0x000000000289e000 Threw 0x00000007d61de300 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.459 Thread 0x000000000289e000 Threw 0x00000007d61e0f68 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.460 Thread 0x000000000289e000 Threw 0x00000007d61e53c8 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.462 Thread 0x000000000289e000 Threw 0x00000007d61ea5d0 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jvm.cpp:1304
Event: 4.506 Thread 0x000000000289e000 Threw 0x00000007d6204350 at C:\re\jdk7u79\2331\hotspot\src\share\vm\prims\jni.cpp:2973

Events (10 events):
Event: 4.466 loading class 0x00000000029f4bd0
Event: 4.466 loading class 0x00000000029f4bd0 done
Event: 4.480 loading class 0x0000000002a2d450
Event: 4.481 loading class 0x0000000002a2d450 done
Event: 4.489 loading class 0x0000000002a2d3f0
Event: 4.489 loading class 0x0000000002a2d3f0 done
Event: 4.489 loading class 0x000000000c7f2540
Event: 4.489 loading class 0x000000000c7f2540 done
Event: 4.505 loading class 0x00000000029e8e40
Event: 4.506 loading class 0x00000000029e8e40 done

Dynamic libraries:
0x00007ff702d80000 - 0x00007ff702db3000     C:\Program Files\Java\jdk1.7.0_79\bin\java.exe
0x00007ffd3d9c0000 - 0x00007ffd3db81000     C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffd3b6e0000 - 0x00007ffd3b78d000     C:\WINDOWS\system32\KERNEL32.DLL
0x00007ffd3aeb0000 - 0x00007ffd3b08d000     C:\WINDOWS\system32\KERNELBASE.dll
0x00007ffd3d7f0000 - 0x00007ffd3d896000     C:\WINDOWS\system32\ADVAPI32.dll
0x00007ffd3b640000 - 0x00007ffd3b6dd000     C:\WINDOWS\system32\msvcrt.dll
0x00007ffd3d730000 - 0x00007ffd3d78b000     C:\WINDOWS\system32\sechost.dll
0x00007ffd3bfd0000 - 0x00007ffd3c0f6000     C:\WINDOWS\system32\RPCRT4.dll
0x00007ffd3b790000 - 0x00007ffd3b8de000     C:\WINDOWS\system32\USER32.dll
0x00007ffd3b0e0000 - 0x00007ffd3b266000     C:\WINDOWS\system32\GDI32.dll
0x00007ffd2dd10000 - 0x00007ffd2df84000     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10240.16384_none_f41f7b285750ef43\COMCTL32.dll
0x00007ffd3b0a0000 - 0x00007ffd3b0d6000     C:\WINDOWS\system32\IMM32.DLL
0x00007ffd3b4e0000 - 0x00007ffd3b63c000     C:\WINDOWS\system32\MSCTF.dll
0x00000000626a0000 - 0x0000000062772000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\msvcr100.dll
0x0000000061ec0000 - 0x0000000062695000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\server\jvm.dll
0x00007ffd3ba30000 - 0x00007ffd3ba38000     C:\WINDOWS\system32\PSAPI.DLL
0x00007ffd371f0000 - 0x00007ffd371f9000     C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffd38a40000 - 0x00007ffd38a63000     C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffd3d8a0000 - 0x00007ffd3d909000     C:\WINDOWS\system32\WS2_32.dll
0x00007ffd3bdf0000 - 0x00007ffd3bdf8000     C:\WINDOWS\system32\NSI.dll
0x0000000000ef0000 - 0x0000000000f1c000     C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffd3a6c0000 - 0x00007ffd3a704000     C:\WINDOWS\system32\cfgmgr32.dll
0x00007ffd38d60000 - 0x00007ffd38d87000     C:\WINDOWS\SYSTEM32\DEVOBJ.dll
0x0000000061eb0000 - 0x0000000061ebf000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\verify.dll
0x0000000061e80000 - 0x0000000061ea8000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\java.dll
0x0000000061e60000 - 0x0000000061e75000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\zip.dll
0x0000000061dc0000 - 0x0000000061dc9000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\attach.dll
0x0000000061e40000 - 0x0000000061e5a000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\net.dll
0x00007ffd39af0000 - 0x00007ffd39b4d000     C:\WINDOWS\system32\mswsock.dll
0x00007ffd24ba0000 - 0x00007ffd24bb5000     C:\WINDOWS\system32\napinsp.dll
0x00007ffd24b80000 - 0x00007ffd24b9a000     C:\WINDOWS\system32\pnrpnsp.dll
0x00007ffd37f70000 - 0x00007ffd37f88000     C:\WINDOWS\system32\NLAapi.dll
0x00007ffd39b50000 - 0x00007ffd39bf8000     C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x00007ffd28c40000 - 0x00007ffd28c4d000     C:\WINDOWS\System32\winrnr.dll
0x00007ffd28b90000 - 0x00007ffd28ba5000     C:\WINDOWS\system32\wshbth.dll
0x00007ffd2ec20000 - 0x00007ffd2ec2a000     C:\Windows\System32\rasadhlp.dll
0x00007ffd36fa0000 - 0x00007ffd36fd8000     C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffd36f50000 - 0x00007ffd36f5b000     C:\WINDOWS\SYSTEM32\WINNSI.DLL
0x00007ffd33090000 - 0x00007ffd330f8000     C:\WINDOWS\System32\fwpuclnt.dll
0x00007ffd3a320000 - 0x00007ffd3a348000     C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffd39c60000 - 0x00007ffd39c77000     C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffd39910000 - 0x00007ffd39943000     C:\WINDOWS\system32\rsaenh.dll
0x00007ffd39cb0000 - 0x00007ffd39ccf000     C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffd3a3f0000 - 0x00007ffd3a403000     C:\WINDOWS\system32\profapi.dll
0x00007ffd3a210000 - 0x00007ffd3a27b000     C:\WINDOWS\system32\bcryptprimitives.dll
0x00007ffd39e40000 - 0x00007ffd39e4b000     C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x00007ffd33d10000 - 0x00007ffd33d26000     C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffd345e0000 - 0x00007ffd345fa000     C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x0000000061e20000 - 0x0000000061e31000     C:\Program Files\Java\jdk1.7.0_79\jre\bin\nio.dll
0x00007ffd36bc0000 - 0x00007ffd36bca000     C:\Users\pkorim\AppData\Local\Temp\jansi-64-7280291655003568062.dll
0x00007ffd37820000 - 0x00007ffd379aa000     C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
java_command: cjmx.Main 8132
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_79
PATH=C:\Program Files\Dell\DW WLAN Card;;C:\Program Files\Java\jdk1.7.0_79\bin;C:\app\client\pkorim\product\12.1.0\client_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\cURL\bin;C:\Users\pkorim.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\apache-maven-3.2.2\bin;C:\Program Files (x86)\WinSCP\;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\scala\bin;C:\Program Files (x86)\sbt\bin;C:\Program Files\SmartBear\SoapUI-5.2.0\bin\;C:\Program Files (x86)\IDM Computer Solutions\UEStudio\;C:\Program Files (x86)\IDM Computer Solutions\UltraCompare\;C:\Program Files (x86)\CMake\bin;C:\Qt\5.4\mingw491_32\bin;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files (x86)\IDM Computer Solutions\IDM Computer Solutions\UEStudio\;C:\Program Files (x86)\Nmap
USERNAME=pkorim
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 61 Stepping 4, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 8.1 , 64 bit Build 9600 

CPU:total 4 (2 cores per cpu, 2 threads per core) family 6 model 61 stepping 4, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, erms, ht, tsc, tscinvbit

Memory: 4k page, physical 8291108k(2179796k free), swap 15106852k(3690464k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (24.79-b02) for windows-amd64 JRE (1.7.0_79-b15), built on Apr 10 2015 12:36:16 by "java_re" with unknown MS VC++:1600

time: Mon Oct 12 14:35:32 2015
elapsed time: 4 seconds

**Comment by mpilquist** [comment]
Thanks for the report. This looks like an issue with jansi, the ANSI library used by SBT. I'll try upgrading to the latest release of SBT and then I'll publish a new snapshot.
