### ISSUE TITLE
double type display have problem

### ISSUE THREAD

**Issue by tomjiang1987** [cjmx/cjmx#20]
I use cjmx to read kafka's jmx info,but some attribute display likely uncorrect

Attributes:
  Count: long
  RateUnit: TimeUnit
  EventType: String
  MeanRate: double
  OneMinuteRate: double
  FiveMinuteRate: double
  FifteenMinuteRate: double

Count: 14270101
  RateUnit: SECONDS
  EventType: bytes
  MeanRate: 12.290604572633972
  OneMinuteRate: 3.328562550729808E-61
  FiveMinuteRate: 9.017959305907854E-11
  FifteenMinuteRate: 0.031762071614678714

the  number of OneMinuteRate don't  like sensible.

**Comment by mpilquist** [comment]
@tomjiang1987 I don't see anything wrong with OneMinuteRate. Note that these are all printed as BigDoubles.
