### ISSUE TITLE
Cannot execute one shot command on remote host

### ISSUE THREAD

**Issue by mbodbg** [cjmx/cjmx#24]
If I execute the following command:

java -cp $JAVA_HOME/lib/tools.jar:target/scala-2.11/proguard/cjmx_2.11-2.6.0-SNAPSHOT.jar cjmx.Main "remote-connect localhost:7091" "mbeans 'java.lang:type=Memory' select *"

I can see that cjmx connects to the remote host, but then executes the first argument ("remote-connect localhost:7091") over and over again:

Connected to remote virtual machine service:jmx:rmi:///jndi/rmi://localhost:7091/jmxrmi
Connection id: rmi://192.168.1.136  3
Default domain: DefaultDomain
6 domains registered consisting of 24 total MBeans
[error] Expected 'mbeans '
[error] Expected 'names'
[error] Expected 'names '
[error] Expected 'describe '
[error] Expected 'select '
[error] Expected 'sample '
[error] Expected 'invoke '
[error] Expected 'disconnect'
[error] Invalid input
[error] remote-connect localhost:7091
[error] ^
[error] Expected 'mbeans '
[error] Expected 'names'
[error] Expected 'names '
[error] Expected 'describe '
[error] Expected 'select '
[error] Expected 'sample '
[error] Expected 'invoke '
[error] Expected 'disconnect'
[error] Invalid input
[error] remote-connect localhost:7091
[error] ^

...

**Comment by mpilquist** [comment]
Sorry about that -- looks like the bug was introduced when the App class was refactored. Fixed in 2.6.1, which is building now and should be on Maven Central in 5m or so.

**Comment by mscg82** [comment]
2.6.1 executes the input command only one time, but is doesn't execute it as a whole, rather it splits the string over spaces and then executes each part, resulting in parse errors. E.g.:

java <classpath params> cjmx.Main "remote-connect 1.2.3.4:5001"

produces two errors:

1. expected ' ' after remote-connect
2. invalid input before 1.2.3.4:5001
