### ISSUE TITLE
sbt has been removed in lastest version

### ISSUE THREAD

**Issue by mbodbg** [cjmx/cjmx#26]
The file "sbt" has been removed in the latest version. 

Building the project as descibed in the README is no longer possible:

To build, run `./sbt publish-local`.  This will build target/scala-2.10/proguard/cjmx_2.12-2.7.0-SNAPSHOT.jar and install a copy to your local ivy cache.

I suppose now it's required to install sbt on the operating system and then run 'sbt publish-local'

**Comment by mpilquist** [comment]
Thanks, updated README with that clarification.
